<?php
$lang = [
    'dashboard_title' => 'Admin Dashboard',
    'welcome' => 'Welcome',
    'menu_dashboard' => 'Dashboard',
    'menu_agen' => 'Agent Data',
    'menu_absensi' => 'Attendance Monitoring',
    'menu_keuangan' => 'Finance & Balance',
    'menu_tiket' => 'Tickets',
    'menu_cuti' => 'Leave Requests',
    'menu_shift' => 'Shift Settings',
    'menu_pengaturan_tiket' => 'Ticket Settings',
    'menu_log' => 'History & Balance Log',
    'menu_payment' => 'Payments',
    'menu_qr_tokens' => 'QR Tokens',
    'menu_paket' => 'Package Settings',
    'menu_mikrotik' => 'MikroTik',
    'dashboard_welcome' => 'This is the main dashboard page.',
    'mikrotik_title' => 'MikroTik Page',
    'back_to_dashboard' => 'Back to Dashboard',
    'menu_pppoe' => 'PPPoE',
    'menu_hotspot' => 'Hotspot',
    'menu_user_profiles' => 'User Profiles',
    'menu_dhcp_server' => 'DHCP Server',
    'menu_netwatch' => 'Netwatch',
    'menu_queue_bandwidth' => 'Queue & Bandwidth',
    'menu_script' => 'Script',
    'menu_firewall' => 'Firewall',
    'menu_log_monitoring' => 'Log Monitoring',
    'menu_panel_monitoring' => 'Customer Monitoring Panel',
    'mikrotik_welcome' => 'Welcome to the MikroTik page.',
    'mikrotik_info' => 'This is the main MikroTik page with dummy menus.',
];
?>
