<?php
$lang = [
    'dashboard_title' => 'Dashboard Admin',
    'welcome' => 'Selamat datang',
    'menu_dashboard' => 'Dashboard',
    'menu_agen' => 'Data Agen',
    'menu_absensi' => 'Monitoring Absensi',
    'menu_keuangan' => 'Keuangan & Saldo',
    'menu_tiket' => 'Tiket',
    'menu_cuti' => 'Request Cuti',
    'menu_shift' => 'Pengaturan Shift',
    'menu_pengaturan_tiket' => 'Pengaturan Tiket',
    'menu_log' => 'History & Log Saldo',
    'menu_payment' => 'Pembayaran',
    'menu_qr_tokens' => 'QR Token',
    'menu_paket' => 'Pengaturan Paket',
    'menu_mikrotik' => 'MikroTik',
    'dashboard_welcome' => 'Ini adalah halaman dashboard utama.',
    'mikrotik_title' => 'Halaman MikroTik',
    'back_to_dashboard' => 'Kembali ke Dashboard',
    'menu_pppoe' => 'PPPoE',
    'menu_hotspot' => 'Hotspot',
    'menu_user_profiles' => 'User Profiles',
    'menu_dhcp_server' => 'DHCP Server',
    'menu_netwatch' => 'Netwatch',
    'menu_queue_bandwidth' => 'Queue & Bandwidth',
    'menu_script' => 'Script',
    'menu_firewall' => 'Firewall',
    'menu_log_monitoring' => 'Log Monitoring',
    'menu_panel_monitoring' => 'Panel Monitoring Pelanggan',
    'mikrotik_welcome' => 'Selamat datang di halaman MikroTik.',
    'mikrotik_info' => 'Ini adalah halaman utama MikroTik dengan menu dummy.',
];
?>
